# Site settings
author: Barrett Yeretzian
title: Barrett Yeretzian
logo: img/profile-pic.png
email: barrettyeretzian@gmail.com
copyright_name: Barrett Yeretzian
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:
github_username: byeretzian
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
